name: fitbitter
description: A Flutter package to make your life easier when dealing with Fitbit APIs.
version: 2.0.1
homepage: https://github.com/gcappon/fitbitter

environment:
  sdk: '>=2.18.0 <4.0.0'
  #flutter: ">=1.17.0"

dependencies:
  dio: ^5.0.1
  flutter:
    sdk: flutter
  flutter_web_auth_2: ^3.1.2
  intl: ^0.19.0
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
